In [32]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [33]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [34]:
x[0][0]


tensor([1, 2, 3])

In [35]:
x[0][0][0]

tensor(1)

In [36]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [37]:
torch.rand(3,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696]])

In [38]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4414, 0.2969, 0.8317, 0.1053],
        [0.2695, 0.3588, 0.1994, 0.5472],
        [0.0062, 0.9516, 0.0753, 0.8860]])
tensor([[0.5832, 0.3376, 0.8090, 0.5779],
        [0.9040, 0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464, 0.7890]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [39]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [42]:
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.1587, 0.6542, 0.3278, 0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666, 0.9811, 0.0874, 0.0041],
        [0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591],
        [0.7653, 0.2979, 0.8035, 0.3813, 0.7860, 0.1115, 0.2477],
        [0.6524, 0.6057, 0.3725, 0.7980, 0.8399, 0.1374, 0.2331],
        [0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249, 0.4340],
        [0.1371, 0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816]])