In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.2


In [8]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [14]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [27]:
#Creating a random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3589, 0.7417, 0.4394, 0.9567],
        [0.1245, 0.0152, 0.0482, 0.8452],
        [0.3476, 0.3492, 0.8092, 0.7744]])

In [28]:
random_tensor.ndim

2

In [30]:
random_image_tensor = torch.rand(size=(3,256,256))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 256, 256]), 3)

In [32]:
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
ones.dtype

torch.float32

In [3]:
one_to_ten = torch.arange(start=0,end=1000,step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [44]:
tenzeros = torch.zeros_like(input=one_to_ten)
tenzeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.dtype

torch.float32

In [7]:
if torch.cuda.is_available():
    print("GPU available")
    
else:
    print("Not available")

Not available


## Three big errors you will run into in machine learning
1. Tensors not right datatype
2. Tensor not in right shape
3. Tensor on right device

In [8]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [11]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

print(f"Device tensor is on: {int_32_tensor.device}")

Device tensor is on: cpu


In [11]:
tensor = torch.tensor([1,2,3])

In [13]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.26 ms, sys: 6.22 ms, total: 8.48 ms
Wall time: 79 ms


In [12]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.73 ms, sys: 3.97 ms, total: 5.7 ms
Wall time: 98.3 ms


tensor(14)

In [15]:
%%time
tensor @ tensor

CPU times: user 36 µs, sys: 5 µs, total: 41 µs
Wall time: 43.9 µs


tensor(14)

In [16]:
torch.rand(3, 2).shape

torch.Size([3, 2])

## Finding the min, max, mean, sum, etc... of tensors

In [4]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [5]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [6]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [7]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [8]:
x.argmin()

tensor(0)

In [9]:
x.argmax()

tensor(9)

In [10]:
x[9]

tensor(90)